### ISSUE TITLE
Task.perform gives an unhelpful error message when the arguments are the wrong way around

### ISSUE THREAD

**Issue by ccapndave** [elm-lang/error-message-catalog#114]
In 0.17:

```
import Task exposing (Task)
import Http

type Msg
  = LoadSuccess String
  | LoadError Http.Error


load : Task Http.Error String
load =
  Http.getString "http://blah"


cmd : Cmd Msg
cmd =
  Task.perform LoadSuccess LoadError load
```

The problem with this program is that `LoadSuccess` and `LoadError` should be the other way around, but the error message from the compiler is:

```
-- TYPE MISMATCH ---------------------------------------------------------------

The 3rd argument to function `perform` is causing a mismatch.

17│   Task.perform LoadSuccess LoadError load
                                         ^^^^
Function `perform` is expecting the 3rd argument to be:

    Task Http.Error String

But it is:

    Task Http.Error String

Hint: I always figure out the type of arguments from left to right. If an
argument is acceptable when I check it, I assume it is "correct" in subsequent
checks. So the problem may actually be in how previous arguments interact with
the 3rd.
```

**Comment by jvoigtlaender** [comment]
This is an instance of https://github.com/elm-lang/elm-compiler/issues/1192. The compiler often prints two types and claims they are different, when actually the two printed types are identical. That happens with type constructors defined as `type alias` (instead of as `type`). And sure enough, whereas `Task.Task` was a `type` before 0.17, it has become a `type alias` in 0.17. That _very strongly_ suggests that what you encounter here is nothing else than the problem already known as https://github.com/elm-lang/elm-compiler/issues/1192. Might want to close here.

**Comment by ccapndave** [comment]
Thanks!  Closing this issue as a duplicate.
