### ISSUE TITLE
Unhelpful message from REPLs ran outside projects

### ISSUE THREAD

**Issue by szabba** [elm-lang/error-message-catalog#124]
If you run the REPL from a directory that's not part of an Elm project I get a rather unhelpful error message:

``` elm
 λ elm repl                       
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 1 + 3
-- SYNTAX PROBLEM --------- elm-stuff/packages/elm-lang/core/3.0.0/src/Array.elm

I ran into something unexpected when parsing your code!

2|     ( Array
       ^
I am looking for one of the following things:

    something like `exposing (..)` which replaced `where` in 0.17
    whitespace


> 
```

I think this doesn't work because dependencies only get installed on a per-project basis. If I'm right, then this should probably be checked for somehow and the user should be informed to create a project before using the REPL.

**Comment by evancz** [comment]
With 0.19.0 the REPL will create a temporary `elm.json` file so that it can evaluate expressions. So this should work now and give access to `elm/core` functions and types.

I think this is true in 0.18 as well, but I'm not certain. I think it at least created an `elm-package.json` in the location where you were running the REPL. I forget.

Anyway, thank you for the report! It should be nicer in more recent versions!
