### ISSUE TITLE
Provide special error hint when "variable name" `as` is used?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/error-message-catalog#139]
``` elm
cons a as = a :: as
```

```
I ran into something unexpected when parsing your code!

6| cons a as = a :: as
          ^
I am looking for one of the following things:

    an equals sign '='
    whitespace 
```

It would be so much nicer if the compiler told the user that the problem is that `as` was read as a keyword, not as a variable name.

**Comment by rtfeldman** [comment]
Thanks for the SSCCE! ❤️

**Comment by evancz** [comment]
Thanks for the report! I am finishing up an overhaul of the parser that produces nicer error messages, and I made a tweak based on this issue. My development branch is now producing:

```
-- RESERVED WORD ------------------------------------------------------ temp.elm

The name `as` is reserved in Elm, so it cannot be used as an argument here:

1| cons a as = a :: as
          ^^
Try renaming it to something else.

Note: This keyword is reserved for pattern matches like ((x,y) as point) where
you want to name a tuple and the values it contains.

```

The message had improved a lot from the overhaul, but https://github.com/elm/compiler/commit/4b6e59853ea2db41e60bae958521a8a0ec8c58d3 is based on this issue and adds a way to explain about `as` in particular since I think that is the most common and most surprising keyword to show up as an argument.
