### ISSUE TITLE
Wrong error message when missing closed parenthesis

### ISSUE THREAD

**Issue by gabriela-sartori** [elm-lang/error-message-catalog#156]
The error is that I don't closed the parenthesis in line 26.
But the error message was not saying nothing about where was the error, and I could not discovered the reason alone, I thought it was a bug.

Suggestion: show a hint saying that maybe it is missing a closed parenthesis, and show the line of the error.

![image](https://cloud.githubusercontent.com/assets/6143964/17778399/40542d7a-653a-11e6-9489-8fdec5231353.png)

![image](https://cloud.githubusercontent.com/assets/6143964/17778410/4838820c-653a-11e6-8c42-5c24c3e920a0.png)

**Comment by ghost** [comment]
The problem seems to have to do with "unfinished expressions followed by a newline character at the end of the file". I found some other code snippets that reproduce this: #161 :
`case True of` + \n
`If True then`\+ \n

**Comment by z5h** [comment]
This seems related:

``` Elm
f = (flip List.foldr) ++
```

Results in a confusing error:

```
I ran into something unexpected when parsing your code!

5|   f = (flip List.foldr) ++
       ^
I am looking for one of the following things:

    end of input
    whitespace

```

When really the fix is:

``` Elm
f = (flip List.foldr) (++)
```

**Comment by evancz** [comment]
Thanks for the report! Going to continue tracking in meta issue #177.

**Comment by evancz** [comment]
@G4BB3R, please include the actual code, not a picture of the code. I have to transcribe it all by hand when it is this way, making it much more time consuming to reproduce.

Here is a similar thing:

```elm
update msg model =
  (model, Cmd.batch [x,y,z]
```

With the new parser, you get this:

![screen shot 2016-12-15 at 4 43 02 pm](https://cloud.githubusercontent.com/assets/1658058/21244943/91e1d486-c2e5-11e6-90b3-114c6822dc24.png)

**Comment by evancz** [comment]
@z5h, your issue is a different thing, so in the future, it is better to open a separate issue. It is actually better to have the same thing from different perspectives, and have it be *my* job to find duplicates. Your assessment may not be correct *and* seeing something five times is a good signal that it is pretty important.

That said, yours is better too:

![screen shot 2016-12-15 at 4 45 07 pm](https://cloud.githubusercontent.com/assets/1658058/21245077/341f43f0-c2e6-11e6-8a9d-fb1b967b0393.png)
