### ISSUE TITLE
Missing function parameter leaves confusing error

### ISSUE THREAD

**Issue by kormie** [elm-lang/error-message-catalog#184]
Error message:
```
Unable to generalize a type variable. It is not unranked.
```

The causing code is as follows:
```elm
jobCompleteText : a -> (a -> Bool) -> Html Msg 
jobCompleteText job =
    let 
        completed =
            jobComplete job 

        style_ : List ( String, String )
        style_ =
            case completed of
                True ->
                    []  
                        |> (::) ( "color", "green" )

                False ->
                    []  
                        |> (::) ( "visiblity", "none" )

        text_ : String
        text_ =
            case completed of
                True ->
                    "Done"

                False ->
                    ""  
    in  
        div []
            [ Html.span [ style style_ ] [ text text_ ] ]
```

The error goes away when a second function parameter is added

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-compiler/issues/1613

Thanks for the SSCCE. Hoping that recent changes will deal with all of these!

**Comment by evancz** [comment]
The root issue _should_ be fixed by https://github.com/elm-lang/elm-compiler/commit/4b25980d93ada12236c794f35570e197be82f787, but this is not actually a http://sscce.org on closer inspection so I cannot verify. I think the easiest path is to see if it is fixed in the next release and reopen if so.

Either way, thanks again!
