### ISSUE TITLE
A little more info would help me diagnose a parameter-type error.

### ISSUE THREAD

**Issue by jessitron** [elm-lang/error-message-catalog#22]
With the code in [this gist](https://gist.github.com/jessitron/e03f07768c55fe1b922c), I get an ordinary type error:

    Detected errors in 1 module.
    ## ERRORS in OneBox.elm ########################################################
    -- TYPE MISMATCH ---------------------------------------------------- OneBox.elm
    The 1st argument to function `start` has an unexpected type.
    6|        StartApp.start 
    7|>  { model = Box.init 
    8|>   , update = Box.update
    9|>   , view = Box.view }
    As I infer the type of values flowing through your program, I see a conflict
    between these two types:
    () -> ()
    ()

I don't know which type is which. (I also can't see here which piece of the record is the wrong type.)
If the error message printed the type signature of function `start`, that would help a lot!

**Comment by andybalaam** [comment]
It would also be helpful to know the name of the field (in the record) for which I am supplying the wrong type.

**Comment by andybalaam** [comment]
Just a note for anyone searching for this error: the argument to `start` requires a `Config` type:

    type alias Config model action = 
        { model : model 
        , view : Address action -> model -> Html 
        , update : action -> model -> model 
        }

The gotcha for me was that I modified the type signature of my `update` function to return `( Model, Effects.Action )` and I needed to change `view` to accept the same type instead of just `Model`, and I needed to change my `init` function (that makes a model) to return the same type (`(Model, Effects.Action)`) instead of just `Model`.

http://package.elm-lang.org/packages/evancz/start-app/2.0.1/StartApp-Simple#Config

**Comment by evancz** [comment]
Here it is in 0.16. Please open a new issue if there are things wrong in the 0.16 message that should be addressed.

![screen shot 2015-10-28 at 1 45 44 am](https://cloud.githubusercontent.com/assets/1658058/10783537/b7020b6c-7d15-11e5-9c01-4692e2fe45ed.png)

**Comment by andybalaam** [comment]
Looks much better, thanks!

**Comment by jessitron** [comment]
oh that's beautiful
