### ISSUE TITLE
failing at string concatenation could have its own error message

### ISSUE THREAD

**Issue by jessitron** [elm-lang/error-message-catalog#38]
When I try to concatenate strings with + it says

```
-- TYPE MISMATCH -------------------------------------------------- Repotron.elm

The left argument of (+) is causing a type mismatch.

22|                "Name: " + repo.name)
                   ^^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    number

    String


Detected errors in 1 module.
```

which is true.
And, it would be super nice if it asked me whether I meant ++, because I spent several minutes looking up how to do string concatenation because I forgot.

**Comment by rtfeldman** [comment]
This is a good candidate for a special case, since in JS you concatenate strings with `+` instead of `++`.

**Comment by evancz** [comment]
For reference, I do read all these issues. So I want to past and future thank you @jessitron for the great suggestions. I am going to let these acrue for a while and take a pass over the compiler to try to do a batch at the same time. This will lead to better results and take less time, so please don't think my lack of response is my lack of care.

I'm not sure if a +1 is a "hey, Evan, look at this". I get why this is useful. @rtfeldman, do you think we can work out a division of labor here? Like, what if I am not subscribed to issue notifications and you are. In that world, you'd be in charge of the feedback. Stuff like:

  * Positive feedback to encourage more reports. Since it is true that I am going to a bunch of these in a big batch, I can imagine people feeling discouraged if they don't hear back for a while. So communicating the process here could really help get more reports.
  * Refining reports. Get people to make their original post explain things best. Self-contained example, existing error output, potential future output. That sort of thing.
  * Curation. If things seem related, maybe start putting tags on them. "Parsing" and "infix" and such.

If you are down, I'll figure out how to add you to the owners of this repo :)

**Comment by rtfeldman** [comment]
I am 100% down for that!

**Comment by evancz** [comment]
Cool, partially done with the process now :)

**Comment by evancz** [comment]
I added a little hint for this :)

![screen shot 2015-10-28 at 4 51 32 pm](https://cloud.githubusercontent.com/assets/1658058/10806634/3756bdb6-7d94-11e5-9717-bd60ac0f48c7.png)

**Comment by rtfeldman** [comment]
This is awesome! :D

Thanks @jessitron for reporting it and @evancz for addressing it!
