### ISSUE TITLE
Polymorphic record accessors: expected = actual

### ISSUE THREAD

**Issue by mgold** [elm-lang/error-message-catalog#68]
If I define record with polymorphic fields, and then make a list of its `.accessors`, I cannot use those accessors on fields of differing types. Though annoying, this isn't new. However, while previous versions reported a conflict between the two types, 0.16 reports that they are the same type. SSCCE:

``` elm
type alias Point a =
  {x : a, y : a}

ints =
  Point 1 2

strings =
  Point "foo" "bar"

fields : List (Point a -> a)
fields =
  [.x, .y]

pairs =
  List.map
    (\f -> (f strings, f ints))
    fields
```

The 0.16 error message is:

```
The argument to function `f` is causing a mismatch.

16|     (\f -> (f strings, f ints))
Function `f` is expecting the argument to be:

    Point String

But it is:

    Point String
```

I've filed this in the error message catalog since, without adding language features, we can do a better job with this error message and maybe even report that the feature is not available. If others think the SSCCE should be valid, I can escalate to an issue on the compiler.

By the way, if the second-to-last line of the SSCCE is replaced with `(\f -> (f ints, f ints))`, it compiles.

**Comment by jvoigtlaender** [comment]
FWIW, I think you are mixing two things that are unrelated. I don't think that the "I'm expecting this, but seeing this (but the two are the same)" has anything to do with polymorphic record accessors specifically. Rather, I think it's simply [this bug](https://github.com/elm-lang/elm-compiler/issues/1192). If so, there's nothing to be done here in terms of creating a better error message. Instead, the compiler needs to be fixed to create a correct error message (one which says that `Point String` and `Point Int` conflict, instead of that `Point String` and `Point String` conflict).

**Comment by mgold** [comment]
Well, if you want to consider the fact that the expected and the actual are _the same_ to be a bug, then yes, it's that bug. And yes, we probably should consider it a bug, so I'm going to close this, and hopefully bring up polymorphic record accessors some other time. So yeah, you're right.
