### ISSUE TITLE
Missing return type of tuple gives misleading error message

### ISSUE THREAD

**Issue by maxhoffmann** [elm-lang/error-message-catalog#74]
Adding type annotations to `StartApp.start` methods I got this error for the `init` function:

```
Detected errors in 1 module.
-- TOO MANY ARGUMENTS ------------------------------------------------- Main.elm

Type Main.Model has too many arguments.

15│ init : Model Effects.Effects Action
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Expecting 0, but got 2.
```

The thing that confuses me is that it says **Expecting 0** although it should expect a tuple:
`init : (Model, Effects.Effects Action)`

**Comment by porglezomp** [comment]
Just a note that this error message is saying that `Model` isn't expecting arguments, that's parsing as `Model` applied to `Effects.Effects` and `Action` instead of `Model` paired with `Effects.Effects Action`.

The problem is that it can't get to the stage in which it reports that `Model Effects.Effects Action` doesn't match `(Model, Effects.Effects Action)` because the former isn't a valid type.

**Comment by maxhoffmann** [comment]
Ah right. Maybe this is a `wontfix` then as it is actually accurate. Thanks!

**Comment by evancz** [comment]
@maxhoffmann, can you edit the initial post to be a http://sscce.org/ where the code that generates the error is also included?

**Comment by evancz** [comment]
I think this will be improved by the changes that assume the type annotation is correct. I cannot test it without an SSCCE, but if you see something like this again with 0.18 or later, please report it!
