### ISSUE TITLE
char is not defined

### ISSUE THREAD

**Issue by ggb** [elm-lang/error-message-catalog#77]
Hello,

I came across a weird error message and I hope this is the right place to report it. I am not sure if it is 'just' a weird message or some kind of bug. 

The following code 

``` elm
import Graphics.Element exposing (show)
import String

detect char chars lim idx acc =
  if lim == 0
    then Nothing
    else 
      case chars of
        (x::xs) ->
          if char == x
            then
              Just (idx, List.reverse acc ++ xs)
            else
              detect char xs (lim - 1) (idx + 1) (x::xs)
        [] ->
          Nothing

main = show <| detect "h" ["e","h","l"] 1 0 []
```

leads to a runtime error which says:

```
char is not defined

Open the developer console for more details.
```

The console shows:

```
Uncaught ReferenceError: char is not defined
```

The Problem is solved by replacing 'char' with something else, for example 'c'. I use the name 'char' in other places without problems. The problem seems to be related to (JavaScript) reserved words: If I replace 'char' with 'byte' the same error message appears.

**Comment by igrep** [comment]
I guess it's not a problem of error message because it causes a runtime error instead of compile-time.
Looks related to https://github.com/elm-lang/elm-compiler/issues/214 .
So reporting to elm-compiler would be good.

And remember to show your environment (Elm, your browser, and OS version) and http://sscce.org/ when submitting.
Perhaps your example should (can) be much smaller.

**Comment by jvoigtlaender** [comment]
The code above gets compiled using tail recursion elimination. So almost certainly the root cause here is the same issue as https://github.com/elm-lang/elm-compiler/issues/1226. Somewhere in the tail recursion elimination code, a call to [`Generate.JavaScript.Variable.safe`](https://github.com/elm-lang/elm-compiler/blob/2521c5e9c03c89354bb0773bdd0bfb3e197b9d32/src/Generate/JavaScript/Variable.hs#L87-L92) is missing. That function is responsible both for replacing `'` in variables by `$` and for prefixing JavaScript keywords (when used as variables) with `$`. The error in https://github.com/elm-lang/elm-compiler/issues/1226 was caused by a variable containing `'`, your error is caused by a variable being a JavaScript keyword. Both errors would be fixed by a call to the `safe` function during code generation. @evancz or @JoeyEremondi should know where that call needs to happen.

**Comment by igrep** [comment]
Oh, sorry for misdiagnosing.

**Comment by jvoigtlaender** [comment]
Oh, @igrep, you didn't misdiagnose at all. It really was essentially the same issue like in https://github.com/elm-lang/elm-compiler/issues/214, just in a part of the compiler that was written only later. (And the `makeSafe` and `jsReserveds` stuff referenced there was refactored/moved since then. But your pointing to https://github.com/elm-lang/elm-compiler/issues/214 helped me see what is amiss here.)

**Comment by jvoigtlaender** [comment]
@ggb, I think the issue can be closed here in the error-message-catalog. You may want to add your example to https://github.com/elm-lang/elm-compiler/issues/1226, but actually I think that is not absolutely necessary. Because `'` and keywords as variable names are handled by the same `safe` function anyway. So when https://github.com/elm-lang/elm-compiler/issues/1226 gets fixed, it should fix your example automatically as well.

**Comment by ggb** [comment]
@jvoigtlaender Thank you! Because it is already addressed/solved, I'll just close this issue :)
