### ISSUE TITLE
Hinting "did you forget to pass arguments" ?

### ISSUE THREAD

**Issue by stoft** [elm-lang/error-message-catalog#78]
As sent to elm-discuss:

As a new user the below error message stumped me for a few minutes before I realized I'd forgotten to pass in the arguments to my function. I really like the compiler and it's "humane" error messages but in this case an additional hint such as "did you forget to pass arguments" or similar may have helped. Unsure whether that's possible. One of the things that threw me off was the fact that it says Virtualdom.Node whereas the docs say Html.

Code to reproduce:

``` elm
import Html exposing (..)

view : Html
view =
  div [] [ foo ]

foo : String -> Html
foo content = text content

main = view
```

Error message:

```
TYPE MISMATCHjump to error
The 2nd argument to function `div` is causing a mismatch.

5|   div [] [ foo ]
Function `div` is expecting the 2nd argument to be:

    List VirtualDom.Node

But it is:

    List (String -> Html)

Hint: I always figure out the type of arguments from left to right. If an
argument is acceptable when I check it, I assume it is "correct" in subsequent
checks. So the problem may actually be in how previous arguments interact with
the 2nd.
```

**Comment by mgold** [comment]
This is happening because `VirtualDom.Node` and `Html` are [the same type](https://github.com/evancz/elm-html/blob/4.0.2/src/Html.elm#L73).

As far back as the original ML (early 70s), type errors referred to the base type instead of the aliased type. Printing the alias in all cases won't work; all `Float`s would become `Time`. Evan is aware of this issue generally. I think one thing we can glean from this specific case is, when the function (like `div`) is from a library, we should use the type annotation from that library to determine what is expected type.

**Comment by igrep** [comment]
@mgold I think the point here is not about type aliases:

> but in this case an additional hint such as "did you forget to pass arguments" or similar may have helped. 

I agreed to this point. It'd be helpful if the compiler hinted that the user should give more arguments to a function.
For example, `ghci` tells a message like this when giving a function with too few arguments:

``` hs
> id
-- ... omitted ... --
      (maybe you haven't applied enough arguments to a function?)
```

@stoft So how about changing the issue title like `Hinting "did you forget to pass arguments"` ?

**Comment by stoft** [comment]
@igrep ty, good idea

**Comment by evancz** [comment]
Here's the slightly updated SSCCE:

``` elm
import Html exposing (..)

view : Html msg
view =
  div [] [ foo ]

foo : String -> Html msg
foo content =
  text content

main =
  view
```

Thanks to #137, it produces the following message now:

![screen shot 2016-08-09 at 10 02 38 pm](https://cloud.githubusercontent.com/assets/1658058/17542397/1ed12b3a-5e7d-11e6-9776-5db1cfd7841a.png)

It may be possible to make it better, but since this is pretty much exactly what folks suggested, I think we should open a new issue if there's something else we should do.
